name: beacon
services:
  overseer:
    image: ghcr.io/pykhaled/overseer:sha256-9cb2087c4475d4cbdfc990c6e94cea989e5f2b000a2e7173019d9bb0500675bc
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  loadbalancer:
    build: ./system-loadbalancer
    env_file:
      - ./system-loadbalancer/.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./system-loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./system-loadbalancer/conf.d:/etc/nginx/conf.d:ro
      - ./system-loadbalancer/ssl:/etc/nginx/ssl:ro
      - ./system-loadbalancer/logs:/var/log/nginx

networks:
  system:
    driver: bridge
    internal: true
