FROM quay.io/keycloak/keycloak:24.0.1

ARG THEME_VERSION=6.1.7

ENV KC_DB=postgres
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

COPY ./singular-keycloak-database-federation/dist /opt/keycloak/providers
COPY ./theme/coursemology-keycloakify-keycloak-theme-${THEME_VERSION}.jar /opt/keycloak/providers/
COPY ./import/coursemology_realm.json /opt/keycloak/data/import/coursemology_realm.json

RUN /opt/keycloak/bin/kc.sh build

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start"]
