apiVersion: nexus.io/target/v1alpha1
kind: DeploymentTarget
id: self-hosted
allowedEnvironments:
  - development
  - production
registryRequiredIn:
  - production
externalSecretsRequiredIn:
  - production
