#!/usr/bin/env bash

set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
repository_root=$(cd "$script_dir/.." && pwd -P)
source_root="$repository_root/system"
output_file="$repository_root/secrets.env"

usage() {
    printf 'Usage: %s [--source DIRECTORY] [--output FILE]\n' "$0"
    printf '\nCollect every service .env file into one root secrets file.\n'
}

while (($# > 0)); do
    case "$1" in
        --source)
            (($# >= 2)) || { printf 'Missing value for --source\n' >&2; exit 2; }
            source_root=$2
            shift 2
            ;;
        --output)
            (($# >= 2)) || { printf 'Missing value for --output\n' >&2; exit 2; }
            output_file=$2
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            printf 'Unknown argument: %s\n' "$1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if [[ ! -d "$source_root" ]]; then
    printf 'Source directory does not exist: %s\n' "$source_root" >&2
    exit 1
fi

source_root=$(cd "$source_root" && pwd -P)
output_directory=$(dirname "$output_file")
if [[ ! -d "$output_directory" ]]; then
    printf 'Output directory does not exist: %s\n' "$output_directory" >&2
    exit 1
fi
output_directory=$(cd "$output_directory" && pwd -P)
output_file="$output_directory/$(basename "$output_file")"

env_files=()
while IFS= read -r env_file; do
    env_files+=("$env_file")
done < <(find "$source_root" -type f -name '.env' -print | LC_ALL=C sort)

if ((${#env_files[@]} == 0)); then
    printf 'No .env files found under %s\n' "$source_root" >&2
    exit 1
fi

for env_file in "${env_files[@]}"; do
    if [[ "$env_file" == "$output_file" ]]; then
        printf 'Output file cannot also be a source file: %s\n' "$output_file" >&2
        exit 1
    fi
done

umask 077
key_inventory=$(mktemp "${TMPDIR:-/tmp}/nexus-env-keys.XXXXXX")
temporary_output=''

cleanup() {
    rm -f "$key_inventory"
    if [[ -n "$temporary_output" ]]; then
        rm -f "$temporary_output"
    fi
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

for env_file in "${env_files[@]}"; do
    relative_path=${env_file#"$repository_root"/}
    awk -v source="$relative_path" '
        {
            line = $0
            sub(/^[[:space:]]*/, "", line)
            sub(/^export[[:space:]]+/, "", line)
            if (line ~ /^[A-Za-z_][A-Za-z0-9_]*[[:space:]]*=/) {
                key = line
                sub(/[[:space:]]*=.*/, "", key)
                print key "\t" source
            }
        }
    ' "$env_file" >> "$key_inventory"
done

if ! awk -F '\t' '
    {
        if ($1 in first_source) {
            if (!reported[$1]++) {
                printf "Duplicate key %s:\n  %s\n", $1, first_source[$1] > "/dev/stderr"
            }
            printf "  %s\n", $2 > "/dev/stderr"
            duplicate_found = 1
        } else {
            first_source[$1] = $2
        }
    }
    END { exit duplicate_found }
' "$key_inventory"; then
    printf 'Resolve duplicate keys before generating %s.\n' "$output_file" >&2
    exit 1
fi

temporary_output=$(mktemp "$output_file.tmp.XXXXXX")
{
    printf '# Generated by scripts/collect-secrets.sh.\n'
    printf '# Regenerate this file after changing a service-level .env file.\n'

    for env_file in "${env_files[@]}"; do
        relative_path=${env_file#"$repository_root"/}
        printf '\n# Source: %s\n' "$relative_path"
        cat "$env_file"
        printf '\n'
    done
} > "$temporary_output"

chmod 600 "$temporary_output"
mv -f "$temporary_output" "$output_file"
temporary_output=''

printf 'Collected %d .env file(s) into %s\n' "${#env_files[@]}" "$output_file"
